### ISSUE TITLE
[IR: turbine js] Cleanup turbine v1 path in turbine js

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-js#205]
## Metadata

Main task: https://github.com/meroxa/product/issues/492

[Intermediate Representation RFC](https://www.notion.so/meroxa/Turbine-Intermediate-Representation-98ee81e4be5648e2a9794b7cb75c9eae).

[Addendum](https://www.notion.so/meroxa/Addendum-Turbine-Intermediate-Representation-RFC-42649002b5fd41efacdcb93f36b61231)

## Context

Remove code paths that allowed creating artifacts via API calls in turbine.

## Acceptance  

- [ ] Remove non IR codepath https://github.com/meroxa/turbine-js/blob/153289b69e12fbd22414d791ec5137c770bf6013/packages/turbine-js-cli/src/runner/primary.ts#L111-L127
- [ ] Remove meroxa-js dependency

**Comment by jkayh** [comment]
closing this for now until reprioritized linked in this [epic](https://github.com/meroxa/product/issues/690) for tracking.
