### ISSUE TITLE
Add Fixture error messages

### ISSUE THREAD

**Issue by anaptfox** [meroxa/turbine-js#84]
## Problem

Currently, we do not provide customers with clear error messaging and resolution steps when there is an issue with their fixtures.

The current error: 
```
Error: node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open '/Users/anaptfox/src/data-apps/liveapp/undefined'] {
```

## Recommendation

If Turbine can't find the fixture for an unspecified source (I didn't add it to `app.json`), it should tell me "Fixture not defined in the application app.json" and give me the steps towards resolving the issue. 

Bonus: Evaluate the ergonomics of defining and mapping fixtures in Turbine data apps. 

## Background

For a software developer to be able to use `meroxa apps run` to run their Turbine data app locally, they must first update/add fixtures to the `app.json` that correspond with what they've written in their code. The configuration in the `app.json` tells Turbine which corresponding fixture belongs to the source defined. 

Here is an example of the default boilerplate, which runs locally by default when there are no changes:

```
exports.App = class App {
  async run(turbine) {
    let source = await turbine.resources("source_name");
    let records = await source.records("collection_name");
    let destination = await turbine.resources("destination_name");
    await destination.write(records, "collection_archive");
  }
};
```

```
{.    "name":"liveapp",
      "language":"javascript",
      "environment":"common",
      "resources": {
               "source_name":"fixtures/demo-cdc.json"
      }
}
```

Here is an example of modified code and what changes would need to happen in the `app.json` file to run locally:

```
exports.App = class App {
  async run(turbine) {
    let source = await turbine.resources("pg_prod");
    let records = await source.records("purchases");
    let destination = await turbine.resources("sf_prod");
    await destination.write(records, "purchase_warehouse");
  }
};
```

```
{.    "name":"liveapp",
      "language":"javascript",
      "environment":"common",
      "resources": {
               "pg_prod":"fixtures/demo-cdc.json"
      }
}
```

**Comment by jkayh** [comment]
Ambiguous error that gets generated:
`Error: node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open '/Users/anaptfox/src/data-apps/liveapp/undefined'] {`
